### ISSUE TITLE
Question, possible bug with flushing the filesystem

### ISSUE THREAD

**Issue by ghollingworth** [relan/exfat#10]
Currently I'm using the exfat fuse driver on a Raspberry Pi derivative device.  We have got a local SATA hard drive which contains an exfat filesystem.

If I run the exfatfsck on the /dev/sda1 whilst it is mounted and I'm writing to the disk some random autogenerated files, I assume what I'm seeing is the errors due to some information not yet written back to the disk which is of course fair enough.

But I then unmount the disk (ready to power it off) and run the exfatfsck again but still get the same errors.  If I try sync'ing it doesn't make any difference....

Only thing that will make the errors go away is to reboot the system completely...

Is this what you'd expect?  I thought once unmounted all outstanding writes should have been made and therefore there should be nothing left to write to the disk...  Is it possible that there is some further caching that is giving me false positives?

Gordon

**Comment by relan** [comment]
> Is this what you'd expect?

No.

> I thought once unmounted all outstanding writes should have been made and therefore there should be nothing left to write to the disk...

That's correct.

> Is it possible that there is some further caching that is giving me false positives?

On unmount fuse-exfat explicitly flushes all data to the physical disk and waits until kernel returns success. There should be no dirty data after this.

I was unable to reproduce this on my Fedora box. Please provide more details: operating system, kernel version, FUSE version, fuse-exfat version, the output of exfatfsck. Do you get any error messages in syslog? Do you use any additional layers like bcache or LVM? Does exfatfsck report errors if you first run sync and then unmount your filesystem?

**Comment by ghollingworth** [comment]
OK, spent some more time running with this, it's not as bad as I thought (isn't that always the way!)  In fact un-mounting the disk does fix up any issues correctly.  I'm not sure why I thought it didn't...

But what we're seeing is occasional (we're talking one in a thousand users once every couple of weeks) with the USB dropping out and the disk being dropped.  Now even if we don't have any files opened for writing we tend to see errors on the disk when rebooted (more than just the standard it wasn't unmounted properly).

What I was hoping was that doing a sync would get the disk into a state where if there was a power loss event it wouldn't end up with disk errors (even if it means increased disk writing and reduced performance)  is there some optional parameter which would allow me to harden it up a little?

Is it possible to reduce the caching at all?

**Comment by ghollingworth** [comment]
One thing that I can get reliably is the following (known bad thing of course...)

1) Attach USB attached exfat formatted drive

    mkdir mnt
    sudo mount /dev/sda1 mnt
    cp file mnt/file1
    sync

2) Oops unplug the hardware
3) Plug it back in again
4) 
    sudo exfatfsck /dev/sda1

lots of errors...

Obviously what I've done is bad, but since I did a sync followed by no further file access I would expect the data to have been sync'd back to the disk do wouldn't expect quite as many errors

Thanks

Gordon

**Comment by relan** [comment]
> Obviously what I've done is bad, but since I did a sync followed by no further file access I would expect the data to have been sync'd back to the disk do wouldn't expect quite as many errors

FUSE does not handle system-wide sync(2) and syncfs(2), only per-file fsync(2) and fdatasync(2). So in your case fuse-exfat just doesn't not know that you've issued a sync. I agree that this is counter-intuitive. Unfortunately, you haven't provided error messages, but I guess you get this:

    ERROR: cluster 0x123 of file 'foo' is not allocated.

This can be fixed at the cost of a slight performance degradation. Could you test fuse-exfat from the `issue10` branch?

**Comment by ghollingworth** [comment]
That definitely cleans up the file system between file accesses, that's awesome.  For the moment I can apply that as a patch in my build system, but it might be useful as a mount option in future.

I think this'll make a big difference in the reliability of our device www.fiveninjas.com thanks for your help

**Comment by relan** [comment]
Great, thanks for testing! I'm going to merge this change into master and release v1.2.2 in a few days after some more testing. No mount option will be required for this new behaviour because one would normally expect FS to function this way. Will it be OK for you?

**Comment by ghollingworth** [comment]
Awesome yes that's great!

**Comment by relan** [comment]
Released the fix in v1.2.2. Thanks!
