### ISSUE TITLE
errors with Ubuntu 14.04

### ISSUE THREAD

**Issue by soldier999** [relan/exfat#102]
Can I update Ubuntu Trusty to a version higher than 1.0.1 in the repository?   I need to avoid the problem caused by Windows lack of support for linux permissions.

**Comment by relan** [comment]
I'd recommend updating to the latest versions of fuse-exfat and exfat-utils as there were a lot of fixes since 1.0.1.

**Comment by soldier999** [comment]
So you think they'll work in Trusty Tahr?  Why does the ubuntu repo only have 1.0.1?

**Comment by soldier999** [comment]
Thank you. I tried to compile from source but ran into issues as a beginner I don't know how to fix.  Are there any detailed instructions for how to compile from your source. Here's the output:
root@david-desktop:/home/exfat# ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FUSE... no
configure: error: Package requirements (fuse) were not met:

No package 'fuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FUSE_CFLAGS
and FUSE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

**Comment by relan** [comment]
> Are there any detailed instructions for how to compile from your source

They are in the readme: https://github.com/relan/exfat/blob/master/README.md

**Comment by soldier999** [comment]
Thanks. Those are the directions I used but they don't explain how to get past the missing fuse problem.

**Comment by relan** [comment]
> Those are the directions I used but they don't explain how to get past the missing fuse problem.

They do. Install libfuse-dev.

**Comment by soldier999** [comment]
Sorry somehow I didn't install libfuse-dev the first time through, however I have now installed it successfully and I don't get the fuse error but I don't think I have the new version of exfat.  Can you tell me how to verify that it's the right version. It may be in the wrong folder or something. Would it matter that I did most of this as root?

**Comment by soldier999** [comment]
How can I verify I've got the newest version running when I reboot?

**Comment by daissi** [comment]
It is quite hard to obtain an update for already released Ubuntu but it is easier to get a backport for Trusty [1]. There is already a bug report for this [2], you can use this bug report to ask them again to backport fuse-exfat.

[1] https://wiki.ubuntu.com/UbuntuBackports
[2] https://bugs.launchpad.net/trusty-backports/+bug/1361869

**Comment by soldier999** [comment]
Thank you so much for your work on exfat-fuse.  I now have 1.2.8.  I appreciate your patience with a beginner who barely understands the basics.
