### ISSUE TITLE
Any router firmware that supports this project?

### ISSUE THREAD

**Issue by l-g** [relan/exfat#112]
Since you wrote "If you have any **questions**, issues, suggestions, bug reports, etc. please create an issue. Pull requests are also welcome!" in the readme...

Do you know of any router firmware (like OpenWRT) where it is reasonably easy to use this project's support for exFat? Something like install the firmware and then use a built in package handler to download and use this project? Or precompiled binaries that you just can upload into /usr/bin/local or similar?

Thank you.

**Comment by relan** [comment]
Unfortunately, I don't know anything about fuse-exfat adoption by routers.
