### ISSUE TITLE
Constanty using 100 % CPU

### ISSUE THREAD

**Issue by l-g** [relan/exfat#113]
I have installed this on my router that runs a fork of Merlin (ASUS WRT) using Entware. When running top this module always run at 100 % (or 99,6 % or something like that) when an disk formatted in exFAT is connected.

```
# uname -a
Linux RT-AC66U-D2F8 2.6.22.19 #1 Tue Nov 27 16:12:51 MST 2018 mips ASUSWRT-Merlin-LTS

```

**Comment by relan** [comment]
Can't say anything without profiling.

**Comment by l-g** [comment]
Any instructions for how to do that?

**Comment by relan** [comment]
No new info for over a year, closing.
