### ISSUE TITLE
this maybe leak memory 

### ISSUE THREAD

**Issue by yuedl** [relan/exfat#114]
fsck occupied 3G memory . this maybe leak memory .  I think the path_length should be checked by path_max(4096).
I have not reproduce it , so there is not log . 
thanks !

**Comment by relan** [comment]
If there's a memory leak I will hardly be able to fix it without reproduction. Valgrind does not report any leaks on my tests.

Paths longer than 4096 chars are perfectly correct from exFAT perspective.

**Comment by relan** [comment]
No new info for over a year, closing.
