### ISSUE TITLE
Becomes dirty after unsuccessful mount

### ISSUE THREAD

**Issue by saproj** [relan/exfat#120]
_Trying to mount a non-dirty volume:_

**mount.exfat-fuse /dev/sdb /mnt/m
FUSE exfat 1.3.0
fuse: device not found, try 'modprobe fuse' first**

_Mount unsuccessful. I fix the problem with the 'fuse' module and retry mount._

**mount.exfat-fuse /dev/sdb /mnt/m
FUSE exfat 1.3.0
WARN: volume was not unmounted cleanly.**

_Mount successful. But the volume is all of a sudden dirty._

**Comment by relan** [comment]
This is not quite correct behavior, but you can safely ignore this warning.

**Comment by relan** [comment]
Fixed in v1.4.0.
