### ISSUE TITLE
Android  9 could not  mount mkexfatfs formatted hard disk

### ISSUE THREAD

**Issue by nilsrennebarth** [relan/exfat#122]
I formatted a 2TB hard disk (MBR partition table, single partition spanning the whole disk) using mkexfatfs under linux, and later tried to access that disk with my samsung s5e tablet running the latest Android version, 9.  It could not access the drive and offered to format it. I let it and compared the output of exfatfsck 1.2.8 before and after. The only difference I found was:

Linux formatted:
Sector size                 512 bytes

Android formatted:
Sector size                   4 KB

Once formatted, the drive is readable and writable by both, Android and Linux. With 'access from Android' I mean, plugging the drive's usb directly into the tablet's USB-C socket using a small adapter. That works, because the disk has an external power supply, i.i. is not powered by its USB connection)

I should note, that formatting smaller (e.g. a 1TB) harddisk and USB Sticks under linux showed no such problem. Unfortunately, the sector size can't be specified on the command line, and googling I could not find much usable information on the topic "sector size" and exfat

**Comment by relan** [comment]
512-byte sector size should not be a problem.

Did you set partition type to 0x07 when you were creating exFAT partition under Linux?

**Comment by relan** [comment]
Closing because there's nothing to do without farther clarification that never followed.
