### ISSUE TITLE
After using it sent errors(Android 9)

### ISSUE THREAD

**Issue by ifForeverlove** [relan/exfat#124]
The errors are below:
01-01 00:09:04.754  2160  2231 E vold    : Mount failed; attempting read-only: No such device
01-01 00:09:04.754  2160  2231 E vold    : public:8,1 failed to mount /dev/block/vold/public:8,1: No such device
I am confused what is the reason of this problem happening?

**Comment by relan** [comment]
I never ported fuse-exfat to Android, so I can't say what's going on here. Please contact the developers of your Android ROM.
