### ISSUE TITLE
Syntax error in configure

### ISSUE THREAD

**Issue by buzzy** [relan/exfat#125]
root@debian:/opt/exfat# ./configure --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf --prefix=/opt/exfat
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-linux-gnueabihf-strip... arm-linux-gnueabihf-strip
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-linux-gnueabihf-gcc... arm-linux-gnueabihf-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-linux-gnueabihf-gcc accepts -g... yes
checking for arm-linux-gnueabihf-gcc option to accept ISO C89... none needed
checking whether arm-linux-gnueabihf-gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of arm-linux-gnueabihf-gcc... gcc3
checking for arm-linux-gnueabihf-gcc option to accept ISO C99... none needed
checking for arm-linux-gnueabihf-ranlib... arm-linux-gnueabihf-ranlib
checking for arm-linux-gnueabihf-ar... arm-linux-gnueabihf-ar
checking the archiver (arm-linux-gnueabihf-ar) interface... ar
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking build system type... x86_64-pc-linux-gnu
checking host system type... arm-unknown-linux-gnueabihf
./configure: line 4113: syntax error near unexpected token `UBLIO,'
./configure: line 4113: `PKG_CHECK_MODULES(UBLIO, libublio,'

**Comment by relan** [comment]
What version of autoconf did you use to generate `configure`?

**Comment by buzzy** [comment]
2.69. The version that comes with Debian Buster

**Comment by relan** [comment]
Works for me on Buster with autoconf 2.69.

What shell do you use (mine is bash)? What is pkg-config version (mine is 0.29)?

**Comment by buzzy** [comment]
docker run -it --rm debian:buster /bin/bash
apt-get update
apt-get -y install build-essential libfuse-dev git autoconf
cd /opt
git clone https://github.com/relan/exfat.git
cd exfat
autoreconf --install
apt-get install --reinstall autoconf
autoreconf --install
./configure
./configure: line 4113: syntax error near unexpected token `UBLIO,'
./configure: line 4113: `PKG_CHECK_MODULES(UBLIO, libublio,'

**Comment by buzzy** [comment]
root@fb49a5c55f6b:/opt/exfat# echo $0
/bin/bash

**Comment by buzzy** [comment]
My bad. I did not have pkg-config installed.
