### ISSUE TITLE
rts5139 can't see devices since I installed this driver

### ISSUE THREAD

**Issue by carz0** [relan/exfat#129]
Hi there
I have a rts5139 card reader. I used to be able to see sd cards, but I needed exfat-utils to access the filesystem with Linux. After I installed exfat-utils, lsblk won't list the card anymore. The card works in other computers. As far as I know, exfat-utils is using this driver in order to work. Could you help me find the driver so I can manually delete it and be able to read cards again? Or we will have a fix for rts5139?

**Comment by relan** [comment]
No idea how exfat-utils can affect lsblk.

lsblk uses own code to detect filesystems, it does not depend on exfat-utils.

Try to remove fuse-exfat (or exfat-fuse, depending on your distro) if it's installed.

**Comment by carz0** [comment]
I'm sorry for opening this. After uninstalling the package, a few restarts and modules deletions I've got it working. Feel free to come it and thanks for your hard work

**Comment by relan** [comment]
Glad you solved the issue.
