### ISSUE TITLE
nonempty option of fuse does not take effect

### ISSUE THREAD

**Issue by hmatrjp** [relan/exfat#131]
I made a pull request to address this. #130

**Comment by biopsin** [comment]
Will this also resolve the mounting exfat issue drives with udevil?
https://github.com/IgnorantGuru/udevil/issues/83
Currently working is fuse-exfat 1.2.8

**Comment by hmatrjp** [comment]
It is possible to be fixed with this, I guess.

Though I myself do not use udevil, the reported symptom is very common
to my case.

2019-08-16 17:40 GMT+09:00, biopsin <notifications@github.com>:
> Will this also resolve the mounting exfat issue drives with udevil?
> https://github.com/IgnorantGuru/udevil/issues/83
> Currently working is fuse-exfat 1.2.8
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/relan/exfat/issues/131#issuecomment-521934559


-- 
濱崎

**Comment by relan** [comment]
Fixed in v1.4.0.
