### ISSUE TITLE
problem mounting exfat usb drive

### ISSUE THREAD

**Issue by reconfigurator** [relan/exfat#135]
I've done all this: https://github.com/relan/exfat
on fedora 30
Found what appears to be the device file (a hint where to look for that after installation might be helpful for less experienced people like me)
I did this and got that:
$ sudo mount.exfat-fuse /dev/disk/by-label/exstorage /mnt/exstorage
FUSE exfat 1.3.0
fuse: bad mount point `/mnt/exstorage': No such file or directory
The usb stick is recognised by name / label in dolphin
Can anyone advise how I can mount this, please?

**Comment by relan** [comment]
> fuse: bad mount point `/mnt/exstorage': No such file or directory

Does `/mnt/exstorage` directory exist?

BTW, you don't have to install fuse-exfat from source on Fedora 30, you can use [RPMFusion](https://download1.rpmfusion.org/free/fedora/releases/30/Everything/source/SRPMS/repoview/fuse-exfat.html).

**Comment by relan** [comment]
Doesn't look like a bug.
