### ISSUE TITLE
Error while doing ./configure --prefix=/usr

### ISSUE THREAD

**Issue by rbeatajane** [relan/exfat#14]
Hi , 

 I was installing fuse-exfat and got the below error while installing, I did the following things to install,
    
    I installed the below packages:
    
    * git
    * autoconf
    * automake
    * pkg-config
    * fuse-devel (or libfuse-dev)
    * gcc
    * make
    
    I got the source code, changed directory and compiled as below:
    
        git clone https://github.com/relan/exfat.git
        cd exfat
        autoreconf --install
        ./configure --prefix=/usr

while ./configure --prefix=/usr , I got the error as below,

[root@Cloud exfat]# ./configure --prefix=/usr
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for FUSE... no
configure: error: Package requirements (fuse) were not met:

No package 'fuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FUSE_CFLAGS
and FUSE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Please help to resolve the issue.

**Comment by relan** [comment]
Which distro do you use? Please make sure you've installed FUSE development package. It's usually called `fuse-devel` or `libfuse-dev`.

**Comment by rbeatajane** [comment]
Thanks a lot .. It worked .. I hadn't installed the fuse-devel. I installed the fuse package and the fuse.ko was inserted into the kernel. what does this fuse-devel contain extra.
