### ISSUE TITLE
Mac to mount exFAT drives with custom block sizes?

### ISSUE THREAD

**Issue by rivertim** [relan/exfat#144]
Mac OSX refuses to see/mount any volume that has been formatted with block/allocation sizes over 2mb. Will your project allow mounting of volumes with block sizes up o 32Mb? Thanks!

**Comment by relan** [comment]
Are you trying to create an FS with mkexfatfs from here and mount it with the macOS built-in driver? What errors does it report?

**Comment by rivertim** [comment]
Hey! I am creating exFat SD & CF cards for use with high-data rate raw video cameras. I format them in mac terminal like this:
sudo newfs_exfat -b 4194304 -v NameIt /dev/disk3s3
The cards record fine in the camera. But Mac OSX cannot mount them in disk utility or command line. The maximum block size it will mount is 1048576 bytes - which is not big enough.
Can your app help me?

**Comment by relan** [comment]
fuse-exfat supports clusters up to 32 MB. Try it.

**Comment by rivertim** [comment]
Oh great!! Many thanks – will do! :)

**Comment by rivertim** [comment]
Installed per instructions on Mac osx 10.14.4 Should disks now mount automatically? I tried 

mount.exfat-fuse /dev/disk3s1 ~/Desktop/folder

I get

-bash: mount.exfat-fuse: command not found

Drive remains unmounted. Have I done something wrong?

**Comment by relan** [comment]
Try to run mount.exfat-fuse from the source tree directory, where you ran `make`:

    sudo ./fuse/mount.exfat-fuse /dev/disk3s1 ~/Desktop/folder

**Comment by rivertim** [comment]
No luck. I did this command:
sudo ./fuse/mount.exfat-fuse /dev/disk3s1 ~/Desktop/folder
gets:
./fuse/mount.exfat-fuse: command not found

If I just do 
cd ./fuse
I get
-bash: cd: ./fuse: No such file or directory
? :(

**Comment by relan** [comment]
Please post the instructions you followed and the output they produced.

**Comment by rivertim** [comment]
Me being dumb. Sorry. I had to do the following to get into root user mode on terminal:

sudo -s

Then re-installed (perhaps not necessary) Ran:

./fuse/mount.exfat-fuse /dev/disk3 /Users/Me/Desktop/folder

The drive mounts!! This is seriously good. I've been searching the web for an answer to this for days! 

Thank you so much for your app – and your patience! :)

**Comment by relan** [comment]
Are you able to read your files?

Automounting is not expected to work, I never figured out how it's implemented in macOS.

**Comment by rivertim** [comment]
Files copy to and from the mount with ease! :) Many thanks!
