### ISSUE TITLE
Why accessing to the struct dirent's member d_type return NULL in exFAT file system? 

### ISSUE THREAD

**Issue by TinusChen** [relan/exfat#147]
In some scenarios, we need to access _d_type_ to get the necessary information for the file.

Why accessing to the struct dirent's member d_type return NULL in exFAT file system? rather than some file systems (among them: Btrfs, ext2, ext3, and ext4 see [man-page](http://man7.org/linux/man-pages/man3/readdir.3.html)) have full support for returning the file type in _d_type_(DT_REG, DT_DIR, etc.).

**Comment by relan** [comment]
d_type was fixed in 5d55e2a922a3d5e24a2141aa5069687dcdb2bca8. Did you try fuse-exfat 1.3.0?

**Comment by TinusChen** [comment]
Thanks for the tip !
