### ISSUE TITLE
Illumos-based  distributions

### ISSUE THREAD

**Issue by hoewweken** [relan/exfat#152]
Hello!

Thanks for this work!

With a small addition to libexfat/platform.h  i can use this driver with OpenIndiana, an illumos-based (solarish) OS:

#elif defined(__sun)

#include <endian.h>
//#include <byteswap.h>
#define exfat_bswap16(x) bswap_16(x)
#define exfat_bswap32(x) bswap_32(x)
#define exfat_bswap64(x) bswap_64(x)
#define EXFAT_BYTE_ORDER __BYTE_ORDER
#define EXFAT_LITTLE_ENDIAN __LITTLE_ENDIAN
#define EXFAT_BIG_ENDIAN __BIG_ENDIAN

**Comment by relan** [comment]
Added in 96ff4f296808410a8546da97134a2f030eb06684. Thanks!
