### ISSUE TITLE
System Panic on newer illumos kernel (2020/09/10)

### ISSUE THREAD

**Issue by hoewweken** [relan/exfat#159]
Thanks for this nice piece of software!
I am using this driver for about half a year now,
after an upgrade of the base system
and rebuild of exfat, the system panics when a fs is mounted.

Please lead me how to get diagnostic info to help any developer solve the issue.

**$ fmdump -Vp  -u fb5fcce4-0a78-65e6-be82-f41d72c5d705**
TIME                           UUID                                 SUNW-MSG-ID
Sep 12 2020 12:04:00.880479000 fb5fcce4-0a78-65e6-be82-f41d72c5d705 SUNOS-8000-KL

  TIME                 CLASS                                 ENA
  Sep 12 12:03:50.3209 ireport.os.sunos.panic.dump_pending_on_device 0x0000000000000000

nvlist version: 0
        version = 0x0
        class = list.suspect
        uuid = fb5fcce4-0a78-65e6-be82-f41d72c5d705
        code = SUNOS-8000-KL
        diag-time = 1599905040 827325
        de = fmd:///module/software-diagnosis
        fault-list-sz = 0x1
        fault-list = (array of embedded nvlists)
        (start fault-list[0])
        nvlist version: 0
                version = 0x0
                class = defect.sunos.kernel.panic
                certainty = 0x64
                asru = sw:///:path=/var/crash/dell/.fb5fcce4-0a78-65e6-be82-f41d72c5d705
                resource = sw:///:path=/var/crash/dell/.fb5fcce4-0a78-65e6-be82-f41d72c5d705
                savecore-succcess = 0
                os-instance-uuid = fb5fcce4-0a78-65e6-be82-f41d72c5d705
                **panicstr = BAD TRAP: type=e (#pf Page fault) rp=fffffe003fc20850 addr=4 occurred in module "fuse" due to a NULL pointer dereference
                panicstack = unix:die+c6 () | unix:trap+1169 () | unix:cmntrap+e9 () | fuse:get_filehandle+52d () | fuse:fuse_open+6e () | genunix:fop_open+96 () | genunix:vn_openat+203 () | genunix:copen+4a9 () | genunix:openat+29 () | unix:brand_sys_syscall+1fe () |** 
                crashtime = 1599904948
                panic-time = 12 September 2020 at 12:02:28 CEST CEST
        (end fault-list[0])

        fault-status = 0x1
        severity = Major
        __ttl = 0x1
        __tod = 0x5f5c9d10 0x347b0b18

**Comment by relan** [comment]
This looks like a kernel bug because user-space programs (like fuse-exfat) should never crash kernel.

Try contacting illumos developers.

**Comment by hoewweken** [comment]
Yes indeed.
Mark this as "solved".

Thanks!
