### ISSUE TITLE
HDD usage does not match file size

### ISSUE THREAD

**Issue by ghollingworth** [relan/exfat#16]
I've got a user who's noticed this problem on the exfat formatted partition.

http://forums.fiveninjas.com/t/hard-drive-fuller-than-what-du-reports/1101

**Comment by relan** [comment]
Thanks for the detailed report! It's a bug in fuse-exfat, I've just released [v1.2.3](https://github.com/relan/exfat/releases/tag/v1.2.3) with the fix. Unfortunately, the only way to reclaim already lost space is to run `chkdsk /f` from Windows.
