### ISSUE TITLE
Is there any difference between using it on Android Q and Android P during integration?

### ISSUE THREAD

**Issue by Yohsing** [relan/exfat#165]
I used to integrating it on Android P successfully，and now i need to do it on Android Q.But when I perform the same operation as before，It didn't run as expected,seems like it can not automount on system.Do you have any good suggestions or solutions?

**Comment by relan** [comment]
I never tried that, hopefully someone here can share their experience.

**Comment by Yohsing** [comment]
![image](https://user-images.githubusercontent.com/51990888/102736585-41939d00-4380-11eb-83ef-febe06df237a.png)

**Comment by relan** [comment]
This is a different project :)
