### ISSUE TITLE
mount.exfat needs a man page on FreeBSD

### ISSUE THREAD

**Issue by FreeBSD-fan** [relan/exfat#168]
The FreeBSD handbook, chapter 18 doesn't disclose how to mount exfat USB drives.  I stumbled upon the solution with an Internet search.  apropos exfat didn't reveal a man page because there isn't one.

**Comment by grahamperrin** [comment]
https://github.com/relan/exfat/blob/master/fuse/mount.exfat-fuse.8

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254186#c3

**Comment by relan** [comment]
The fuse-exfat project has a manpage. Closing as there's nothing to do on my side.
