### ISSUE TITLE
we meet "configure: error: Package requirements (fuse) were not met" on ubuntu16.04 about  exfat

### ISSUE THREAD

**Issue by jim-qiu** [relan/exfat#179]
we get the code from https://github.com/relan/exfat,and then the steps are following:
1.  cd exfat
2.  autoreconf --install
3.  ./configure

**Comment by relan** [comment]
Did you install libfuse-dev?

**Comment by jim-qiu** [comment]
> Did you install libfuse-dev?

after I run "sudo apt install libfuse-dev",now we run "./configure",we can generate the Makefile,thanks.

**Comment by relan** [comment]
Some custom Android ROMs integrated fuse-exfat, but I never tried that myself.

**Comment by jim-qiu** [comment]
The android version of our device is android 10,we do not find fuse-exfat
