### ISSUE TITLE
warning when autoreconf --install  @ubuntu 22.04 LTS 

### ISSUE THREAD

**Issue by jiamn** [relan/exfat#183]
configure.ac:30: warning: The macro `AC_PROG_CC_C99' is obsolete.
configure.ac:30: You should run autoupdate.
./lib/autoconf/c.m4:1659: AC_PROG_CC_C99 is expanded from...
configure.ac:30: the top level

gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by relan** [comment]
Fixed in v1.4.0.
