### ISSUE TITLE
mount fail

### ISSUE THREAD

**Issue by Freelifeww** [relan/exfat#186]
system:Ubuntu 21.04
root cmd:mount.exfat-fuse /dev/sda1 /mnt
log:
FUSE exfat 1.3.0
ERROR: failed to read boot sector.

**Comment by relan** [comment]
This means an I/O error. Most probably a hardware issue.

**Comment by Freelifeww** [comment]
> This means an I/O error. Most probably a hardware issue.

Thanks ，I check the hardware
