### ISSUE TITLE
Fsck.exfat -y flag not working

### ISSUE THREAD

**Issue by thefanum** [relan/exfat#187]
When I try to run fsck.exfat with any flags, -y -a included, it automatically inserts n for no, instead of y. Leaving the filesystem broken, and unrepaired. 

Expected behavior: remove corrupt files when told to.

Exact error: 
ERROR /file/location/filename.ext first cluster is wrong. Truncate (y/N)

And even interactive mode doesn't allow me to interact, just inserts N on my behalf. 

Ubuntu 22.04.1
Util.linux 2.37.2
Exfatprogs 1.1.3

**Comment by relan** [comment]
>  Exfatprogs 1.1.3

This project provides exfat-utils. Wrong site :)
