### ISSUE TITLE
Sry, im stupid but how do install on Mac?

### ISSUE THREAD

**Issue by Akrota** [relan/exfat#189]
Hey,

englisch is not my native lang and it seems that im a bit stupid, but how do I install this on Mac haha

I downloaded everything but don't know what to do with the stuff (main stuff + autoconf etc)

also copied the commands in terminal and let that run through

got 
"Cloning into 'exfat'...
remote: Enumerating objects: 3594, done.
remote: Counting objects: 100% (183/183), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 3594 (delta 106), reused 140 (delta 88), pack-reused 3411
Receiving objects: 100% (3594/3594), 719.37 KiB | 10.58 MiB/s, done.
Resolving deltas: 100% (2306/2306), done.
zsh: command not found: autoreconf
zsh: no such file or directory: ./configure
make: *** No targets specified and no makefile found.  Stop."

after make install 

"make: *** No rule to make target `install'.  Stop."

___

I just tried it with https://ports.macports.org/port/exfat-utils/ 
but I think it just won't fix my problem with my hard drive :D

**Comment by relan** [comment]
> I just tried it with https://ports.macports.org/port/exfat-utils/
> but I think it just won't fix my problem with my hard drive :D

Well, no luck then :-/

**Comment by Anonyame** [comment]
I made it work on a Big Sur macOS release. You should install macFUSE or OSXFUSE first to install this instance.

**Comment by Anonyame** [comment]
Install with the source code could be a better choice. Neither Homebrew nor macPorts could work, during my workflow.

**Comment by Anonyame** [comment]
> Install with the source code could be a better choice. Neither Homebrew nor macPorts could work, during my workflow.

Oh, however you may need Homebrew or macPorts to install some packages, but during my work flow it could be replaced by conda, including autoconf, automake, as well as pkg-config. Just need to set a env var to let pkg-config to read the config file from the true path.
