### ISSUE TITLE
repair VBR

### ISSUE THREAD

**Issue by beku** [relan/exfat#19]
exfat as a internal partition can not be repaired from OS X or Linux. Adding a repair capability would be appreciated.

In my case the exfat VBR is affected. The ssd partition in question can be mounted and looks fine. But exfatfsck stops at the checksum and does not act about.

Here the tools (from current git) output:
exfatfsck 1.2.3
ERROR: invalid VBR checksum 0x55dbf46 (expected 0x79e6f9c3).

**Comment by relan** [comment]
Yes, repair capability would be cool. There is already task about it, see #3.
