### ISSUE TITLE
I execute command"brew install --HEAD exfat" got an error.This is the log

### ISSUE THREAD

**Issue by wangshuzhi888** [relan/exfat#190]
==> Cloning https://github.com/relan/exfat.git
Updating /Users/shuzhi/Library/Caches/Homebrew/exfat--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at cdd8f98 Fix a couple of typos in comments.
==> Installing exfat from gmerlino/exfat
==> autoreconf -fiv
==> ./configure --prefix=/opt/homebrew/Cellar/exfat/HEAD-cdd8f98
Last 15 lines from /Users/shuzhi/Library/Logs/Homebrew/exfat/02.configure:
checking host system type... aarch64-apple-darwin22.1.0
checking for pkg-config... /opt/homebrew/Library/Homebrew/shims/mac/super/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libublio... no
checking for fuse... no
configure: error: Package requirements (fuse) were not met:

No package 'fuse' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FUSE_CFLAGS
and FUSE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Do not report this issue to Homebrew/brew or Homebrew/core!

exfat's formula was built from an unstable upstream --HEAD.
This build failure is expected behaviour.
Do not create issues about this on Homebrew's GitHub repositories.
Any opened issues will be immediately closed without response.
Do not ask for help from MacHomebrew on Twitter.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

i will ready install fuse.how to fix this error.

**Comment by relan** [comment]
Do you have [macFUSE](https://osxfuse.github.io/) installed?

**Comment by Anonyame** [comment]
This repo has nothing to do with the exfat on Homebrew. You should try to install the macFUSE or OSXFUSE, then clone the repo and follow the instruction to install. You may want to use Homebrew or macPorts to install some packages, however you could complete everything with only a conda virtual env.
