### ISSUE TITLE
The question about exFAT specification.

### ISSUE THREAD

**Issue by parker040180** [relan/exfat#20]
I am a student and interested in exFAT.
I want to understand the mechanism of exFAT in more detail, but i can't find the officially released exFAT specification.
You complete this great implementation.
Can you tell me what is you according to and do you have any recommended document of exFAT?
Thank you!!!

**Comment by relan** [comment]
I didn't write any documentation while I was doing reverse engineering. So all I have is code.

Wikipedia has links to some technical docs that can help you: https://en.wikipedia.org/wiki/ExFAT#External_links
