### ISSUE TITLE
Build on OpenBSD?

### ISSUE THREAD

**Issue by swatting** [relan/exfat#21]
Hi.

I am missing the build instructions for OpenBSD. And a installable package would be nice... :)

Best regards
  swatting

**Comment by relan** [comment]
Hi,

OpenBSD support was added by another person, not me. I've never worked with OpenBSD, so I can hardly help you with it. If you figure out the instructions and post them here I can add them to the README.

**Comment by swatting** [comment]
Hi.

I don't know the commands - can you give me the contact for the other 
person, perhaps we can do it together?

Thanks

**Comment by xx404** [comment]
Which version of OpenBSD are you using? I just successfully compiled it on OpenBSD 5.6 and 5.8. I'm going to assume you have a fresh install of OpenBSD 5.8.

Do everything as root to keep things simple (I assume this is not a production machine!)

Install the required packages.

    export PKG_PATH=http://ftp.openbsd.org/pub/OpenBSD/`uname -r`/packages/`uname -m`/
    pkg_add git automake autoconf

Choose automake-1.15 (option 6)
Choose autoconf-2.69p1 (option 16)

    cd /root
    export AUTOCONF_VERSION=2.69
    export AUTOMAKE_VERSION=1.15
    git clone https://github.com/relan/exfat.git
    cd exfat
    autoreconf --install
    ./configure --prefix=/usr/local
    make
    make install

The differences between this and the Linux instructions are that you need to specify the versions of automake and autoconf in environment variables and that OpenBSD no longer comes with sudo preinstalled.

**Comment by swatting** [comment]
Hi.

I am using 5.8.

With your how to it works! Many thanks!!! :)

**Comment by relan** [comment]
Added to the README.md in 74cb90633f9f9c36952f7bd3d8cc539a17be786e. Thanks!
