### ISSUE TITLE
File written under Linux does not show up on Windows

### ISSUE THREAD

**Issue by jmixton** [relan/exfat#22]
# Problem
A file that is created on an exFAT medium under Linux doesn't show up in the Windows Explorer.

Not sure whether this is related to #13.

# Versions
  * Windows 8.1
  * openSUSE 13.1, x86_64
    * exfat 1.2.3

# Reproducing
1. Created filesystem with Windows 8.1

2. Created test file `testwin.txt` under Windows 8.1

3. Mounted with Linux
    ```bash
    mount.exfat /dev/loop0 /mnt/mnt/
    cat /mnt/mnt/testwin.txt
    (expected contents)
    joe /mnt/mnt/testlin.txt
    cat /mnt/mnt/testlin.txt
    (expected contents)
    umount /mnt/mnt
    sync
    ```
4. Mounted with Windows
  - `testwin.txt` is there as expected
  - `testlin.txt` is **not** shown

5. Executed file system check with Windows
  - now both files are there as expected with the expected contents

# Expectation
Both files should already be there after Step 4.

**Comment by jmixton** [comment]
Following #13 I also tried
```bash
lin:~ # exfatfsck /dev/loop0
exfatfsck 1.2.3
Checking file system on /dev/loop0.
File system version           1.0
Sector size                 512 bytes
Cluster size                 32 KB
Volume size                1023 MB
Used space                  480 KB
Available space            1023 MB
Totally 1 directories and 3 files.
File system checking finished. No errors found.
lin:~ # mkdir /tmp/sd
lin:~ # mount.exfat-fuse /dev/loop0 /tmp/sd
FUSE exfat 1.2.3
lin:~ # echo hello > /tmp/sd/test
lin:~ # sync
lin:~ # umount /tmp/sd
lin:~ # exfatfsck /dev/loop0
exfatfsck 1.2.3
Checking file system on /dev/loop0.
File system version           1.0
Sector size                 512 bytes
Cluster size                 32 KB
Volume size                1023 MB
Used space                  512 KB
Available space            1023 MB
Totally 1 directories and 4 files.
File system checking finished. No errors found.
lin:~ # mount.exfat-fuse /dev/loop0 /tmp/sd
FUSE exfat 1.2.3
lin:~ # cat /tmp/sd/test
hello
lin:~ # umount /tmp
```
But no file `test` is found if I plug the device back into the Win 8.1 machine.

**Comment by relan** [comment]
Thanks for the detailed report! I tried this test case on Windows 7 and it worked fine. Unfortunately I don't have Windows 8.1 nearby. Could you share a compressed image of the filesystem with `testlin.txt` and `testwin.txt`? I'd like to compare directory entries of those two files and figure out the difference between them.

**Comment by jmixton** [comment]
Hm. Can't reproduce it anymore, when trying with fresh media/images. Tried several times with slightly different approaches, but always working as expected.

Right now my best guess is that somehow the medium in question has been corrupted before.

Sorry for the noise.

**Comment by relan** [comment]
> Right now my best guess is that somehow the medium in question has been corrupted before.

> Sorry for the noise.

No problem. Please make a copy of the FS and reopen this issue if you experience this problem again.

**Comment by relan** [comment]
I think I've reproduced this problem. Looks like Windows 8.1 caches the list of directory entries across reboots. If I unmount and mount the FS in Windows (via Disk Management Console) it shows the new file that has been added under GNU/Linux. Actually `chkdsk` fixes this issue because it also unmounts and mounts (thus invalidating the cache); it makes no changes to the FS at all.

**Comment by heftig** [comment]
Windows 8 and later are known to actually do hibernation when you request a shutdown. This feature is known as Fast Boot and should be disabled.

**Comment by relan** [comment]
> Windows 8 and later are known to actually do hibernation when you request a shutdown. This feature is known as Fast Boot and should be disabled on a dual-booting machine.

Seems so, thanks for the explanation!

> If exFAT has a "dirty" flag like NTFS, the driver could refuse to open such filesystems read-write in order to avoid problems with stale caches after resume from hibernate. ntfs-3g behaves like this.

exFAT has dirty flag. But unlike NTFS, exFAT is mostly used for external drives and users often unplug them without proper unmount. Enforcing people to repair FS is such case will cause much more complains, than the problem described in this issue. Also, it's not an option until there is a free tool to do this.

**Comment by feoff3** [comment]
Maybe helpful for someone.
I had the same issue with CentOS 7 and Windows 10, EXFAT FUSE version 1.2.7
I built exfat fuse from the source (version 1.3.0) and the issue gone. 

PS thanks for the working driver ;)
