### ISSUE TITLE
Failed to build in Mac OS X 10.10.5

### ISSUE THREAD

**Issue by duckychen** [relan/exfat#23]
I've installed automake.
However, I failed to build in configure step.
Here is the message I got:

./configure --prefix=/usr
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... none needed
checking for ranlib... ranlib
checking for ar... ar
checking the archiver (ar) interface... ar
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
./configure: line 4080: syntax error near unexpected token `FUSE,'
./configure: line 4080: `PKG_CHECK_MODULES(FUSE, fuse)'

**Comment by relan** [comment]
Could you post `configure` somewhere so that I could have a look at it?

Also please post the versions of autoconf, automake, OSXFUSE and Xcode.

**Comment by duckychen** [comment]
Thanks for your prompt reply.
:)

My `configure` is in 
https://www.dropbox.com/s/u3wjtpf1vjsv1zh/configure?dl=0

Here are versions of my toolchain:
autoconf: 2.69
automake: 1.15
OSXFUSE: 2.0
XCode: 7.2
Mac OS X: 10.10.5

**Comment by relan** [comment]
Looks like you haven't installed `pkg-config`. Install it, remove `configure` and run `autoreconf -i` again. The new `configure` should work.

> OSXFUSE: 2.0

This is probably a typo, but please ensure that you use the latest OSXFUSE version (2.8.3).

**Comment by duckychen** [comment]
Thanks!!
I will try about this!
