### ISSUE TITLE
Is it possible to mount a device file as loopback device with mount.exfat?

### ISSUE THREAD

**Issue by ark-ark** [relan/exfat#24]
I am trying to combine mount.exfat with libbde to mount a BitLocker encrypted exFAT device using OpenSuse. 

After following the instructions ( https://github.com/libyal/libbde/wiki/Mounting ) I have a device file that I'm trying to mount.

```
mount.exfat -o loop,ro /mnt/bdevolume/bde1 /mnt/exfat_file_system
> FUSE exfat 1.2.3
> fuse: mount failed: Block device required
```

Is there any way to mount the device file?

**Comment by relan** [comment]
Try this:

    mount -t exfat -o loop,ro /mnt/bdevolume/bde1 /mnt/exfat_file_system

Make sure that `mount.exfat` symlink is installed and points to `mount.exfat-fuse`.

**Comment by ark-ark** [comment]
Ah, the symlink was missing. That did the trick. Thank you!

**Comment by moneytoo** [comment]
But how to pass the ``-d`` option that enables debug output to shell?

**Comment by relan** [comment]
Use `-o debug`, it does the same.
