### ISSUE TITLE
please help!!

### ISSUE THREAD

**Issue by Mohammad123450** [relan/exfat#28]
Hi sir... I want to resize .img file on kali linux, I have downloaded and successfully mounted an exFat system on my laptop, but i resize2fs is not working, nothing happen and i cannot stop that

resize2fs 1.42.12 (29-Aug-2014)

I got this and it don't stop :(

**Comment by relan** [comment]
Hi,

resize2fs works only with ext2, ext3 and ext4 filesystems. AFAIK there is no way to resize exFAT.

**Comment by Mohammad123450** [comment]
@relan I want to resize ext3 on exfat 
I haven't explained well..

**Comment by relan** [comment]
Oh, now I see. Could you post the exact commands you use to create and resize ext3 image?

**Comment by Mohammad123450** [comment]
really i have created that img file using linux deploy(on android), but these are the commands : dd if=/dev/zero of=linux.img bs=1024 count=1048576
mkfs -t ext3 linux.img
e2fsck -f (location)/linux.img
resize2fs (location)/linux.iimg (size(M))

**Comment by relan** [comment]
This project does not support Android. You are using a 3rd party port to Android. Please contact the author of the port.
