### ISSUE TITLE
Automount and install from source code.

### ISSUE THREAD

**Issue by danwerspb** [relan/exfat#29]
OS - Ubuntu 14.04. I remove previous version exfat by command 'sudo apt-get remove exfat-fuse exfat-utils'. Then compiling from source by instruction. Mount exfat partitions work correctly, but only if i mount manually. Automount capability lost. How return this capability?
![2016-02-08 01 06 22](https://cloud.githubusercontent.com/assets/4201995/12875668/3cbfc506-ce00-11e5-8c7b-e36537014e87.png)

**Comment by relan** [comment]
To make automounting work you need to install the binaries into a proper directory (instead of default `/usr/local/sbin`). Unfortunately, it varies from distro to distro. For Ubuntu 14.04 try this:

    # remove binaries from /usr/local/sbin
    sudo make uninstall
    # change install directory (yes, there is nothing after "=")
    ./configure --prefix=
    # install binaries into /sbin
    sudo make install

**Comment by danwerspb** [comment]
T7hanks
