### ISSUE TITLE
Repairing functionality in fsck

### ISSUE THREAD

**Issue by relan** [relan/exfat#3]
Current implementation of fsck utility is very simple and can only check file systems. Repairing is not supported but many people want it. It's a very complex task that will hardly ever be done by myself. Volunteers are welcome!

**Comment by unxed** [comment]
should bad sectors check be submitted as another issue or not?

**Comment by relan** [comment]
I think bad sectors check request can be left here.

**Comment by leeminghao** [comment]
Do you have this plan?

**Comment by relan** [comment]
> Do you have this plan?

I don't have any plans to implement this.

**Comment by relan** [comment]
Basic implementation released in v1.3.0, please file a new issue if you get an error exfatfsck can't fix.
