### ISSUE TITLE
license

### ISSUE THREAD

**Issue by christopherpow** [relan/exfat#31]
I know I had a discussion with you previously about licensing. But I've lost that history. I am wondering of the possibility of re-license under a less restrictive license like BSD? Why was GPLvX chosen? I would very much like to port this to a proprietary RTOS but can't because of the GPL barrier. We are, however, allowed to use BSD licensed source. Thoughts? I'd be OK with a "no way in hell" answer, but if that is the case I'd appreciate feedback on what is the pull for GPLvX. Thanks!

**Comment by relan** [comment]
> I am wondering of the possibility of re-license under a less restrictive license like BSD?

I will _not_ relicense my code under a permissive license. Besides, I'm not the only copyright holder, there are other contributors.

> Why was GPLvX chosen?

There is a Russian proverb: good must have fists. I believe that freedoms must be protected. Permissive licenses do not provide such protection.

> I would very much like to port this to a proprietary RTOS but can't because of the GPL barrier.

GPL does not prohibit porting to a proprietary OS. I can help you incorporate the required changes (if you publish them under GPL of course). This will be a win for everyone.

**Comment by christopherpow** [comment]
I agree it doesn't prohibit. However, the sticking point comes in distribution. I believe I have a story for why we don't need to release source code for our operating system when releasing source code for our proprietary RTOS' implementation of EXFAT [the 'major components of an OS distribution' exception]. However, it's proving impossible to convince others of this. I'm but a small cog. :|
