### ISSUE TITLE
fsync failed: Input/output error

### ISSUE THREAD

**Issue by necktwi** [relan/exfat#34]
Just made a fresh install. `sudo mount.exfat-fuse /dev/sda1 /mnt/exfat` execution remained at `FUSE expat 1.2.3` several minutes and finally it threw `WARN: volume was not unmounted cleanly.`
`ERROR: fsync failed: Input/output error.`

**Comment by relan** [comment]
This means hardware failure: your disk is dying. If you don't have a backup copy, try to make an image of your exFAT partition using dd and then mount it as a loop device to extract data.

**Comment by relan** [comment]
Hardware issue.
