### ISSUE TITLE
manual not installed by default

### ISSUE THREAD

**Issue by kucharskim** [relan/exfat#35]
Default make install target doesn't include manual pages. I guess this is because `no-installman` option for automake in `configure.ac`. Would you consider including manual pages too in make install target?

**Comment by relan** [comment]
Various systems install manpages differently, e.g. compress them using `gzip` or `xz`. So I deferred this to package managers. But you are right, documentation absence is not a good thing.

**Comment by kucharskim** [comment]
That is true about compressing manual pages. Personally I like to leave manual pages uncompressed and allow maintainers of packages compress them on their own with compression of their choice. OpenBSD for example doesn't compress manual pages at all. I think that is simplest solution and should cover most of the bases.

**Comment by relan** [comment]
Fixed in v1.2.4.
