### ISSUE TITLE
unable to cleanup a node with 1 references.

### ISSUE THREAD

**Issue by kucharskim** [relan/exfat#36]
Empty, but previously used and rm -rf'd via fuse-exfat SDXC card, mounted with following command:

```
# mount.exfat-fuse /dev/sd2i /mnt 
FUSE exfat 1.2.3
# echo $?
0
# pgrep -lf fuse                                                               
19864 mount.exfat-fuse /dev/sd2i /mnt
```

In another terminal as non-root user, I do:

```
$ touch /mnt/a                                                                 
$ rm -f /mnt/a
rm: /mnt/a: Resource temporarily unavailable
```

Back in the other shell, where I mounted sd-card I see:

```
# BUG: unable to cleanup a node with 1 references.
# pgrep -lf fuse | wc -l
       0
# dmesg | grep fuse
fuse: device close without umount
```

This is on:

```
# sysctl -n kern.version                                                       
OpenBSD 6.0-beta (GENERIC.MP) #2123: Wed May 25 14:04:11 MDT 2016
    deraadt@amd64.openbsd.org:/usr/src/sys/arch/amd64/compile/GENERIC.MP
```

**Comment by kucharskim** [comment]
I can reproduce it every time. After re-mounting the file-system I can see file gone, after rm(1).

**Comment by relan** [comment]
Thanks for a good bugreport!

This does not happen on GNU/Linux, only on OpenBSD (checked on 5.9 i386). I've found an easier reproducer:

```c
#include <fcntl.h>
#include <err.h>
#include <unistd.h>

int main()
{
	int fd = open("/tmp/t/a", O_CREAT, 0);
	if (fd < 0)
		err(1, "failed to create file");
	close(fd);
	return 0;
}
```

It causes the following sequence of FUSE callbacks (`fuse_exfat_getattr` are omitted):

```
DEBUG: [fuse_exfat_create] /a 0100000.
DEBUG: [fuse_exfat_open] /a.
DEBUG: [fuse_exfat_release] /a.
```

Both `fuse_exfat_create` and `fuse_exfat_open` take references, but there is only one `fuse_exfat_release`. Thus, we get a dangling node (on `umount` there will be message about non-zero reference counter). Actually I wouldn't expect `fuse_exfat_open` to be called at all in this case.

@xx404, what do you think?

**Comment by kucharskim** [comment]
I you guys need any help with testing, I'm happy to help.

**Comment by relan** [comment]
JFYI: I've emailed @xx404 about this issue (he's the author of FUSE for OpenBSD) about 3 weeks ago but still no reply. So, I'm afraid I can't help you with this bug unless you wish to dive into the OpenBSD-specific part yourself.

**Comment by relan** [comment]
Could you report this issue to OpenBSD mailing lists?

**Comment by relan** [comment]
Closing as there's nothing to do on fuse-exfat side.
