### ISSUE TITLE
Large files appear corrupted under Linux, unless using Windows 7

### ISSUE THREAD

**Issue by rogerxxxx** [relan/exfat#40]
Using Git exfat fuse dated July 14 2016, I'm seeing few (if any) hangs while mounting now.  Also no apparent hangs while using /bin/ls on the exfat filesystem.

However the following errors still exist where I cannot copy or view files larger than a certain size, and the files will appear corrupted under Linux.  Using Windows 7, I have no problems viewing or copying the same files.

Appears each large file (ie. JPEG, MP4) has a corrupt clusters.  I did change from the default 64KB to 128KB cluster size to try to avert this issue without any success.

EXFAT FSCK OUTPUT
./exfatfsck /dev/sdd1                                                                                      
exfatfsck 1.2.4                                                                                                                                                          
Checking file system on /dev/sdd1.                                                                                                                                       
File system version           1.0                                                                                                                                        
Sector size                 512 bytes                                                                                                                                    
Cluster size                128 KB                                                                                                                                       
Volume size                  58 GB                                                                                                                                       
Used space                   21 GB                                                                                                                                       
Available space              36 GB                                                                                                                                       
ERROR: file '07141240_0006.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141300_0007.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141320_0008.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141340_0009.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141400_0010.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141533_0011.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141553_0012.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141608_0013.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141628_0014.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141648_0015.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141708_0016.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141728_0017.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141748_0018.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141808_0019.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141817_0020.MP4' has invalid cluster 0xfffffff7.                                                                                                          
ERROR: file '07141843_0021.MP4' has invalid cluster 0xfffffff7.                                                                                                          
Totally 4 directories and 22 files.                                                                                                                                      
File system checking finished. ERRORS FOUND: 16.

SYSLOG: MOUNTING THE FILESYSTEM
Jul 14 20:16:07 localhost4 kernel: usb 1-1.3: new high-speed USB device number 15 using ehci-pci                                                                         
Jul 14 20:16:07 localhost4 kernel: usb 1-1.3: New USB device found, idVendor=4255, idProduct=1000                                                                        
Jul 14 20:16:07 localhost4 kernel: usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3                                                                   
Jul 14 20:16:07 localhost4 kernel: usb 1-1.3: Product: Storage                                                                                                           
Jul 14 20:16:07 localhost4 kernel: usb 1-1.3: Manufacturer: Ambarella                                                                                                    
Jul 14 20:16:07 localhost4 kernel: usb 1-1.3: SerialNumber: 123456789ABC                                                                                                 
Jul 14 20:16:07 localhost4 kernel: usb-storage 1-1.3:1.0: USB Mass Storage device detected                                                                               
Jul 14 20:16:07 localhost4 kernel: scsi host16: usb-storage 1-1.3:1.0                                                                                                    
Jul 14 20:16:07 localhost4 mtp-probe[26233]: checking bus 1, device 15: "/sys/devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3"                                            
Jul 14 20:16:07 localhost4 mtp-probe[26233]: bus: 1, device: 15 was not an MTP device                                                                                    
Jul 14 20:16:08 localhost4 kernel: scsi 16:0:0:0: Direct-Access     AMBA     Storage          v1.0 PQ: 0 ANSI: 0                                                         
Jul 14 20:16:08 localhost4 kernel: sd 16:0:0:0: Attached scsi generic sg4 type 0                                                                                         
Jul 14 20:16:08 localhost4 kernel: sd 16:0:0:0: [sdd] 120946688 512-byte logical blocks: (61.9 GB/57.7 GiB)                                                              
Jul 14 20:16:08 localhost4 kernel: sd 16:0:0:0: [sdd] Write Protect is off                                                                                               
Jul 14 20:16:08 localhost4 kernel: sd 16:0:0:0: [sdd] Mode Sense: 8f 00 00 08                                                                                            
Jul 14 20:16:08 localhost4 kernel: sd 16:0:0:0: [sdd] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA                                             
Jul 14 20:16:09 localhost4 kernel:  sdd: sdd1                                                                                                                            
Jul 14 20:16:09 localhost4 kernel: sd 16:0:0:0: [sdd] Attached SCSI removable disk

SYSLOG: ERROR DURING FILE COPY OPERATION
Jul 14 20:13:32 localhost4 kernel: scsi_io_completion: 4 callbacks suppressed                                                                                            
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 4e 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: 4 callbacks suppressed                                                                                            
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 85512                                                                                  
Jul 14 20:13:32 localhost4 kernel: buffer_io_error: 4 callbacks suppressed                                                                                               
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6593, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 4f 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 85768                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6625, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 50 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 86024                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6657, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 51 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 86280                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6689, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 52 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 86536                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6721, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 53 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 86792                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6753, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 54 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 87048                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6785, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 55 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 87304                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6817, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 56 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 87560                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6849, async page read                                                                     
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:13:32 localhost4 kernel: sd 14:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 01 57 08 00 00 08 00                                                               
Jul 14 20:13:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 87816                                                                                  
Jul 14 20:13:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 6881, async page read

SYSLOG: ERROR DURING EXFAT FSCK
Jul 14 20:16:34 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00                                                        
Jul 14 20:16:34 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 00 08 00 00 08 00
Jul 14 20:16:34 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 8
Jul 14 20:16:34 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul 14 20:16:34 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 00 08 00 00 08 00
Jul 14 20:16:34 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 8
Jul 14 20:16:34 localhost4 kernel: Buffer I/O error on dev sdd, logical block 1, async page read
Jul 14 20:16:47 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul 14 20:16:47 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 80 20 00 00 40 00
Jul 14 20:16:47 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 32800
Jul 14 20:16:47 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul 14 20:16:47 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 9a f0 00 00 10 00
Jul 14 20:16:47 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 39664
Jul 14 20:16:47 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul 14 20:16:47 localhost4 kernel: sd 16:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 9a 08 00 00 08 00
Jul 14 20:16:47 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 39432
Jul 14 20:16:47 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 833, async page read
Jul 14 20:17:34 localhost4 kernel: udevd[1640]: worker [26251] /devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.3/1-1.3:1.0/host16/target16:0:0/16:0:0:0/block/sdd/sdd1 is taking a long time

**Comment by relan** [comment]
Those `I/O error` messages mean that your USB stick is dying. Windows tries to mitigate this by writing 0xfffffff7 values into cluster map, but this makes little sense on modern storage devices that have own remapping facilities.

**Comment by rogerxxxx** [comment]
Using the "extended scan" option for the Windows 7 Scan Disk on the exfat device partition results in zero errors being reported.

I am now noticing after connecting the device successfully and prior to doing anything with the device, I get the following errors just after successful connection.

This almost seems like a portable device driver incompatibility with the Linux USB mass storage driver?

Jul 15 15:38:46 localhost4 kernel:  sdd: sdd1
Jul 15 15:38:46 localhost4 kernel: sd 17:0:0:0: [sdd] Attached SCSI removable disk

Jul 15 15:39:06 localhost4 kernel: sd 17:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul 15 15:39:06 localhost4 kernel: sd 17:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 00 08 00 00 08 00
Jul 15 15:39:06 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 8
Jul 15 15:39:06 localhost4 kernel: sd 17:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul 15 15:39:06 localhost4 kernel: sd 17:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 00 08 00 00 08 00
Jul 15 15:39:06 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 8
Jul 15 15:39:06 localhost4 kernel: Buffer I/O error on dev sdd, logical block 1, async page read
Jul 15 15:39:32 localhost4 kernel: sd 17:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul 15 15:39:32 localhost4 kernel: sd 17:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 80 08 00 00 08 00
Jul 15 15:39:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 32776
Jul 15 15:39:32 localhost4 kernel: sd 17:0:0:0: [sdd] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x00
Jul 15 15:39:32 localhost4 kernel: sd 17:0:0:0: [sdd] tag#0 CDB: opcode=0x28 28 00 00 00 80 08 00 00 08 00
Jul 15 15:39:32 localhost4 kernel: blk_update_request: I/O error, dev sdd, sector 32776
Jul 15 15:39:32 localhost4 kernel: Buffer I/O error on dev sdd1, logical block 1, async page read

**Comment by relan** [comment]
What kind of device is this? Is it USB flash drive?

How do you connect it to you Linux PC? Do you use a USB hub or you plug in directly into the motherboard USB port?

Is Windows installed on the same PC? Do you connect you drive to it in the same way?

**Comment by rogerxxxx** [comment]
This is basically a GoPro device having internal flash media.  Connected to both USB-2 or USB-3 ports results in the same errors, using motherboard USB connectors and using no external USB hubs.

Same computer, dual boot into Windows 7 and Windows 10, using natively Gentoo.  I also tried using the Fedora-24 Live CD/USB, resulting in similar errors.

I've never seen the "[sdd] tag#0 UNKNOWN(0x2003)" errors with any other devices.  Shrugs.  My only thoughts are something is being done oddly on the portable device.

**Comment by rogerxxxx** [comment]
Also mounted in read-only mode (ie. -o ro) and still the same exact problems.

**Comment by relan** [comment]
This is definitely not a `fuse-exfat` issue because it's kernel that fails to read data from the device. Try to report this to LKML.
