### ISSUE TITLE
More informative error message for fuse_loop(3) failure

### ISSUE THREAD

**Issue by mmcco** [relan/exfat#44]
FUSE's man pages describe `fuse_loop(3)` as follows:

> `fuse_loop()` is the main loop of a FUSE program.  This function looks for FUSE requests from the kernel and responds to them using the `struct fuse_operation` present in the structure `fuse`.  It will return only if something goes wrong or if the kernel sends a `FUSE_DESTROY` opcode to libfuse.

It seems that a failure of this function suggests a general failure of the FUSE filesystem. However, fuse-exfat currently reports "FUSE loop failure" to stderr. It seems like it would be better to use a more general error message that users not familiar with FUSE internals can understand. Maybe something as simple as "FUSE filesystem crashed".

Thanks for your time,
Michael

**Comment by relan** [comment]
I agree that "FUSE loop failure" doesn't sound very good. The problem with this message is that it does not give users any idea about how to fix this error.

**Comment by relan** [comment]
The "FUSE loop failure" message is gone after f61d4279d14582d56b039f3ed7b49f5989600c86.
