### ISSUE TITLE
unable to re-partition exfat sd card

### ISSUE THREAD

**Issue by punzilla** [relan/exfat#49]
Hi there,

I have a samsung 128 mb sd card that I had attached to my samsung s5 phone (which is not rooted). 
I plugged in my Samsung S5 to my mac and used a "adb shell sm partition disk:179,128 mixed 50" command to partition the card to 50 % adoptable storage and 50 % standard SD.

Recently I received an error message on my phone advising that the 'adopted' internal part of the sd card had become corrupted. 

I am not in a position where I need to recover the data on the SD card, I would just like to re-partition the SD card and start again from scratch. It doesn't appear that any app is allowing me to do so.

I've tried on various devices eg...
On a rooted android device (not my phone) I tried running the app Aparted to re-partition the sd card.
On a my mac I've tried running disk doctor for re-partitioning to no avail.
I've also attempted to run g-parted and fdisk from a virtual ubuntu partition to no avail,
and also attempted to use the mini partition tool on a Windows machine to no avail.

I've tried running a exfat fsk this has not found any issues. 
It detects the first partition /dev/sdb1 though fails to recognise the /dev/sdb2 and /dev/sdb3 partitions.

>osboxes@osboxes:~$ sudo exfatfsck /dev/sdb1
exfatfsck 1.2.4
Checking file system on /dev/sdb1.
File system version           1.0
Sector size                 512 bytes
Cluster size                128 KB
Volume size                  60 GB
Used space                 9670 MB
Available space              50 GB
Totally 1207 directories and 3966 files.
File system checking finished. No errors found`

Even though I can see the partition I can't seem to make changes.

> Disk /dev/sdb: 119.8 GiB, 128579534848 bytes, 251131904 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 752570F2-9E31-4886-B607-C4B575E548BD

>Device         Start       End   Sectors  Size Type
/dev/sdb1       2048 125566975 125564928 59.9G Microsoft basic data
/dev/sdb2  125566976 125599743     32768   16M unknown
/dev/sdb3  125599744 251131870 125532127 59.9G unknown

Any assistance would be much appreciated.

Thank you.

**Comment by relan** [comment]
What is your Android version? Do you use stock or custom ROM?

> I am not in a position where I need to recover the data on the SD card, I would just like to re-partition the SD card and start again from scratch. It doesn't appear that any app is allowing me to do so.

Why do you need an app if you've successfully done this previously using Android built-in `sm` utility? Why not just wipe the SD card and repartition it again in the same way?

**Comment by punzilla** [comment]
Hi there,
I'm using Android version 6.0.1 and I'm using a stock ROM, model number SM-G900I.
I have attempted to re-partition the disk from within the adb shell, though this fails.

> Shines-MBP:files Shine$ sudo ./adb.osx shell
Password:
shell@klte:/ $ sm list-disks
disk:179,64
shell@klte:/ $ sm partition disk:179,64 mixed 50                               
Error: java.lang.IllegalStateException: command '21 volume partition disk:179,64 mixed 50' failed with '400 21 Command failed'

My Mac OSX advises that my sd card is not writable. All the apps that I've used appear to perform the task to format or repartition though once it completes, I'll re-insert the sd card and the same files appear.

If you have any suggestions please let me know.

It appears as though I'm not the only one who has experienced a similar issue for example http://forums.androidcentral.com/ask-question/642725-not-able-delete-format-contents-samsung-sd-card-android-one-cell.html.

Any help would be greatly appreciated. I'm out of ideas.

Thank you.

**Comment by relan** [comment]
Try to zero out the card. From a Mac:

    dd if=/dev/zero of=/dev/rdiskN bs=1m

Where rdiskN is the memory card device (note that it's not rdiskNsM).

**Comment by punzilla** [comment]
Hi there, 

Last night I tried the command
dd if=/dev/zero of=/dev/disk2 bs=1m

No error messages reported but when i put the sd card back into my phone it reverted back to how it was before. 

I'll reattempt tonight using 

dd if=/dev/zero of=/dev/rdisk2 bs=1m

I'll let you know the outcome.

**Comment by punzilla** [comment]
Hi there, 

I have run the 

> Shines-MBP:~ Shine$ sudo dd if=/dev/zero of=/dev/rdisk2 bs=1m
Password:
dd: /dev/rdisk2: Input/output error
122624+0 records in
122623+0 records out
128579534848 bytes transferred in 3133.369892 secs (41035543 bytes/sec)

So input / output error. At least this was the first command that gave me something meaningful. Until this point, I've been convinced that it has been caused by a software glitch. 

Though it is still quite interesting that 
a. The photos on my non encrypted partition are still visible. 
b. The sd card is not writeable. 
c. No formatting or partitioning has appeared to be possible.

I'd still be interested to hear your comment in relation to this. 

Thank you for your assistance. 

Unless you have any further suggestions, it may be time to purchase another SD card :S

**Comment by relan** [comment]
I/O error means hardware failure. I'd replace this SD card.

**Comment by relan** [comment]
Closing this issue as it has nothing to do with this project.

**Comment by punzilla** [comment]
Thanks for your assistance.
