### ISSUE TITLE
Multiple files having the same name but a different case in different directories

### ISSUE THREAD

**Issue by anthonyryan1** [relan/exfat#50]
I seem to be seeing an issue where multiple files having the same name (but with a different case) causes problems.

Reproduction steps: 
```
# within a newly created exfat mount
git clone https://github.com/torvalds/linux.git
cd linux
git status
```
Expected result
```
Git reporting no changes
```
Actual result
```
	modified:   include/uapi/linux/netfilter/xt_CONNMARK.h
	modified:   include/uapi/linux/netfilter/xt_DSCP.h
	modified:   include/uapi/linux/netfilter/xt_MARK.h
	modified:   include/uapi/linux/netfilter/xt_RATEEST.h
	modified:   include/uapi/linux/netfilter/xt_TCPMSS.h
	modified:   include/uapi/linux/netfilter_ipv4/ipt_ECN.h
	modified:   include/uapi/linux/netfilter_ipv4/ipt_TTL.h
	modified:   include/uapi/linux/netfilter_ipv6/ip6t_HL.h
	modified:   net/netfilter/xt_DSCP.c
	modified:   net/netfilter/xt_HL.c
	modified:   net/netfilter/xt_RATEEST.c
	modified:   net/netfilter/xt_TCPMSS.c
```

Now the pattern I saw here was that the problematic file names all appear with different cases within the linux code base here. I've tried recreating a few with the correct case and it appears to simply invert the case of the other file in those tests.

I've tested this on exfat 1.2.5 + kernel 4.9 and exfat 1.2.4 + kernel 4.4 to reproduce these results.

**Comment by relan** [comment]
exFAT is case-insensitive by design. So, that's the expected behaviour.
