### ISSUE TITLE
Infinite loop in readdir() in node.c

### ISSUE THREAD

**Issue by ytrezq** [relan/exfat#59]
[It seems`rc = read_entries(ef, parent, &entry, 1, *offset);`fetch the current entry](https://cloud.githubusercontent.com/assets/3824869/24026517/f85d98a2-0ac1-11e7-8761-314ef2130c56.png).

Just list the hidden directory entry content located inside the root directory.
The expected result is to throw an error instead of emptying laptops batteries.

**Comment by relan** [comment]
Fixed in `robustify` branch. Thanks!

N.B. Excessive error message is printed:

    invalid cluster 0x18 while reading
    failed to open directory '/..R'

**Comment by relan** [comment]
Fixed in v1.2.7.
