### ISSUE TITLE
Infinite loop inside rootdir_size.

### ISSUE THREAD

**Issue by ytrezq** [relan/exfat#60]
It seems just using`exfat_mount()`[on this](https://cloud.githubusercontent.com/assets/3824869/24027827/a254e8f8-0aca-11e7-8cb3-615961bbf6d5.png) will cause`exfat_next_cluster`inside`rootdir`to fetch the current cluster instead of the next cluster.

**Comment by relan** [comment]
Fixed in `robustify` branch. Thanks!

**Comment by ytrezq** [comment]
@relan : What append to the`robustify`branch ?

**Comment by relan** [comment]
It was merged into `develop` branch.

**Comment by ytrezq** [comment]
@relan : which commit ?

**Comment by relan** [comment]
There are multiple: 9dc649a5af99950c25b5aaaa3ce17f6fdcf1381a, cb1a999dced311d534f3167667ea1721fa5a71f8, 688a6fb6a4bc49c2e18b2ce8fadc1e0d1bd20ad3, abab1c28f20f1084a22f8289c6af81faeb328ee9, 717d36e85bdd5cc31793621d230ce4466cb70d44, 2f6a54823b8069e9f02b5ece1e6b77307f808283.

**Comment by relan** [comment]
Fixed in v1.2.7.
