### ISSUE TITLE
When the eject exfat format U disk will report some errors

### ISSUE THREAD

**Issue by JackieLiu1** [relan/exfat#61]
Hello @relan 
I have an error about exfat-fuse here，When I click on the right mouse button eject, the kernel error message is as follows:
```
[  200.567159] sd 6:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  200.567171] sd 6:0:0:0: [sdb] tag#0 Sense Key : Not Ready [current]
[  200.567179] sd 6:0:0:0: [sdb] tag#0 Add. Sense: Medium not present
[  200.567186] sd 6:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 00 a0 00 00 f0 00
[  200.567191] blk_update_request: I/O error, dev sdb, sector 160
[  200.619342] sd 6:0:0:0: [sdb] tag#0 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  200.619351] sd 6:0:0:0: [sdb] tag#0 Sense Key : Not Ready [current]
[  200.619358] sd 6:0:0:0: [sdb] tag#0 Add. Sense: Medium not present
[  200.619365] sd 6:0:0:0: [sdb] tag#0 CDB: Read(10) 28 00 00 00 01 90 00 00 10 00
[  200.619370] blk_update_request: I/O error, dev sdb, sector 400
```
Another way is the same error
```
mount.exfat /dev/sdb1 /mnt -o nonempty
umount /dev/sdb1 && eject /dev/sdb1
```
My operation system is Ubuntu 16.10  linux kernel is 4.10.0+

can you help me ?

Thanks
BR 
JackieLiu

**Comment by JackieLiu1** [comment]
Open the kernel CONFIG_USB_STORAGE_DEBUG option，format the U disk file system for ext4 and exfat, get the dmesg information as follows:
[exfat.txt](https://github.com/relan/exfat/files/860148/exfat.txt)
[ext4.txt](https://github.com/relan/exfat/files/860149/ext4.txt)
in exfat-fuse, you can see that there are a few READ command after the START_STOP command,
in ext4, is clear.
I think it is the error caused by several read and write commands after START_STOP

**Comment by JackieLiu1** [comment]
By the way, Ntfs-3g also reported the same errors, but the kernel file system will not, I think it may be a fuse problem.

I am here to find a way to close this problem, but do not know why, so ask for your help
```
mount.exfat /dev/sdb1 /mnt -o nonempty
umount /dev/sdb1 && sleep 1 && eject /dev/sdb1
```

**Comment by relan** [comment]
No ideas, unfortunately. I'd suspect hardware issue. Did you try another USB stick?

**Comment by JackieLiu1** [comment]
Thank you for your reply, I do not think it is a hardware problem, I tried four different manufacturers of U disk device, will have the same error, even worse, when opening the kernel CONFIG_SCSI_MQ_DEFAULT switch, will lead usb-storage process Use 100%, and then crash

BR

**Comment by relan** [comment]
Do you get those errors when you simply write something to the device from user space? I mean without any FS, just `dd`, for example.

**Comment by JackieLiu1** [comment]
Yep, Test your idea a few minutes ago, the kernel reports the same problem
```
dd if=/dev/zero of=/dev/sdb1 bs=1M count=1M oflag=direct
```
at the same time, another terminal run
```
eject /dev/sdb1
```

`dmesg`  information  is similar, But I think this should really be reported this type of error, because it is in the write data when the eject.

**Comment by relan** [comment]
So, it's not FUSE. Try to report this issue to LKML.

**Comment by JackieLiu1** [comment]
Is it ? OK, Thanks again. I will submit it to LKML

**Comment by c384mb** [comment]
Is necessary to consider still this fact, if during record on usb flash make reset or turn off the power, possible to receive the broken files. I have seen this in Guest OS in VirtualBox. Check is made by means of chkdsk (exFAT) in Windows Host. At me such breakage of files happens not seldom, if to make reset Guests OS. Guest machines sometimes happens too freezes.

**Comment by relan** [comment]
exFAT is not have any means of power outage resistance (and TexFAT is a different story).

Closing as there's no new info for over a year.
