### ISSUE TITLE
exit with 'abort()' on attemp of directory creation when run with stderr closed

### ISSUE THREAD

**Issue by asashnov** [relan/exfat#62]
Initially found on Ubuntu 16.04 (but not reproduced on Ubuntu 14.04)
and it reproduces with "Latest commit 01d1175 on Jan 29":

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial

$ uname -a
Linux builder-Standard-PC-i440FX-PIIX-1996 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
$ sudo apt-get build-dep exfat-fuse

$ git clone https://github.com/relan/exfat.git
$ cd exfat
$ autoreconf --install
$ ./configure
$ make

$ sudo make install

$ dd if=/dev/zero of=fsimage.bin bs=1M count=100

$ ./mkfs/mkexfatfs fsimage.bin

$ sudo losetup /dev/loop0 /home/user/exfat/fsimage.bin

$ mkdir 12

```
Run with stderr closed:
`$ sudo sh -c "strace -o /home/user/log.txt /usr/local/sbin/mount.exfat-fuse /dev/loop0 /home/user/exfat/12 2>&- "
`
Creation a directory will cause 'abort()':
```
$ mkdir 12/hello
mkdir: cannot create directory ‘12/hello’: Software caused connection abort

```

**Comment by relan** [comment]
Is there anything from fuse-exfat in syslog?

**Comment by asashnov** [comment]
Yes, but those messages are probably misleading:
```
Mar 24 11:12:07 builder-Standard-PC-i440FX-PIIX-1996 mount.exfat-fuse: unexpected entry type 0 after 0xffffffff at 0/3
Mar 24 11:12:07 builder-Standard-PC-i440FX-PIIX-1996 mount.exfat-fuse: freeing non-existing cluster 0x162f740 (0x63d5)

```

Don't look at them ;)

Instead, see a difference between two strace logs when mounted with stderr closed and without.
When stderr is open, before folder creation you will see lot of communications between fd 3 and 4.
When stderr is closed, active communication happens between fd 2 and 3.

Probably stderr fd=2 is hardcoded somewhere and when prints a message this intersects another communication channel with bad data (causes kind of parse error).

**Comment by relan** [comment]
I've made a simple reproducer (tested on Fedora 25):

```c
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>

int main()
{
	int fd1 = open("/dev/null", O_RDWR);
	int fd2 = open("/dev/null", O_RDWR);
	int fd3 = open("/dev/null", O_RDWR);
	fprintf(stderr, "Desc %d %d %d\n", fd1, fd2, fd3);
	return 0;
}
```

Command:

    sh -c 'strace -o log.txt ./a.out 2>&-'

Relevant part from the strace log:

```
open("/dev/null", O_RDWR)               = 2
open("/dev/null", O_RDWR)               = 3
open("/dev/null", O_RDWR)               = 4
write(2, "Desc 2 3 4\n", 11)            = 11
```

So, program starts with file descriptor 2 (STDERR_FILENO) closed, opens a file, OS returns the first free descriptor which appears to be 2, stdio functions assume that `stderr` is always 2 (they cannot known about all those manipulations).

In fuse-exfat case (when stderr is closed) we get descriptor 2 assigned to /dev/loop0. No surprise everything turns into a mess. A solution I can see here is to open /dev/null until we get a descriptor number greater than 2 and only after that open the device (assuming that OS allocates file descriptors sequentially). What do you think?

**Comment by asashnov** [comment]
I don't remember any recommendation on this.
My first though was just exit immediately if one of stdin, stdout or stderr is closed.
GNU Coding Standard says nothing on that.

Google: what program should do if stderr is closed
pointed me to page 24 of 'Secure Programming Cookbook for C and C++: Recipes for Cryptography'
It says program should test if descriptor is open with fstat() 0, 1 and 2 and do open("/dev/null") if not.
Similar behaviour I can see with strace on ntfs-3g (which works with stderr closed). It seems to be a good idea.

**Comment by relan** [comment]
Pushed fix into the `issue62` branch. Thanks for pointing out!

**Comment by asashnov** [comment]
Well done!
I checked ' git clone -b issue64 ' now and it works now!
Directories was successfully created and no other crashes.
lsof shows descriptors 0 1 2 -> /dev/null, 3 -> /dev/loop0,  4-> /dev/fuse

**Comment by relan** [comment]
Thanks for checking!
