### ISSUE TITLE
Is umask working?

### ISSUE THREAD

**Issue by nemonein** [relan/exfat#63]
Hello.
I'm using Kubuntu 17.04(64bit).

I mounted exfat partition(formatted in Windows10) in fstab.
`UUID=xxxx-xxxx /mnt/somewhere      exfat        rw,uid=1000,gid=1000,dmask=0002,fmask=0002 0 0`

Then, I made a file in /mnt/somewhere by touch.
```
$ touch sample
$ ls -l
-rwxrwxr-x 1 userA userA      0  4월 19 23:51 sample
```
I expected to see `rw-rw-r--` but the result is `rwxrwxr-x`. Is it normal?
It seems that umask is working but executable bit is always added, regardless of umask.
If I set the same option for fat32 drive, it works as I expected.

What I want to do is not to give a executable bit to the files in exfat.

**Comment by relan** [comment]
Hi,

> I expected to see rw-rw-r-- but the result is rwxrwxr-x. Is it normal?

Yes. Mask consists of bits that will _not_ be permitted. See `man mount`.

> If I set the same option for fat32 drive, it works as I expected.

Are you sure? I get the same result with the same umask for fuse-exfat and vfat. I'm on Fedora 25.

> What I want to do is not to give a executable bit to the files in exfat.

Then you need `fmask=111`.

**Comment by nemonein** [comment]
I'm sorry. I should have googled more.
fmask=111(what I really wanted was fmask=113) works fine. Thank you very much.

And, about fat32, you were right. The result is the same for both exfat and vfat.

Thank you again. :smile:

**Comment by relan** [comment]
No problem. I'm glad it now works for you just as you want it to work. :)
