### ISSUE TITLE
How compile for android?

### ISSUE THREAD

**Issue by daradan** [relan/exfat#64]
Hi.
Sorry for my English.
Can you help me?!
How I need compile for android device for arm64-v8a, armeabi, armeabi-v7a and etc like [here](https://github.com/Lurker00/Android-fs/releases/download/1.0.4/UPDATE-android-fs-1.0.4-install.zip)?
Thank you!

**Comment by relan** [comment]
I've never tried to build fuse-exfat for Android.

But this branch should be a good start for you: https://github.com/relan/exfat/tree/android

**Comment by daradan** [comment]
Oh, thank you. I try it.
