### ISSUE TITLE
Plans to Migrate to libfuse 3.x.x?

### ISSUE THREAD

**Issue by githububub** [relan/exfat#67]
Is support for libfuse 3.x.x on the horizon?

**Comment by relan** [comment]
Yes. Currently it's in the `libfuse3` branch. Would be cool if you could test it.

**Comment by githububub** [comment]
Build failed against `fuse3` and `fuse-common` from official repositories (3.0.2) and against custom `fuse3` and `fuse-common` (3.0.2) builds. Build Log: https://pastebin.com/fTFCkAzs and PKGBUILD: https://pastebin.com/tYEuuKH2

**Comment by relan** [comment]
Thanks for testing! Looks like I'll have to merge `simplefuse` first, which breaks OpenBSD support :(.

**Comment by hsuethan** [comment]
Hi Relan

I am trying to build it on branch (libfuse3),
I encountered the same error as githububub.

**Comment by relan** [comment]
I know. That branch is a work-in-progress.

**Comment by relan** [comment]
Done in v1.4.0.
