### ISSUE TITLE
cannot create symbolic link?

### ISSUE THREAD

**Issue by takboo** [relan/exfat#68]
When i cp some file from ubuntu to my Thumb Drive base on exFAT, i got those error:

```
cp: cannot create symbolic link '../remove_drive/source-data/source-code/aosp-mirror-tuna/.repo/manifests.git/hooks/pre-auto-gc': Function not implemented

```

is there a way to fix this?
PS: I can not replace exFAT to another filesystem.

**Comment by relan** [comment]
exFAT does not support symlinks, but `cp` can dereference them:

    -L, --dereference  
           always follow symbolic links in SOURCE

**Comment by takboo** [comment]
Thanks. but this problem is not just use cp command. I was use `repo` to pull android open source project (aosp) from storage.googleapis.com. When i use `repo` on mac. everything is fine. but when  i use it on ubuntu with exFAT, i got `Function not implemented` error as I describe above.

**Comment by relan** [comment]
> When i use repo on mac. everything is fine

Do you run `repo` on Mac on exFAT file system?

BTW, exFAT is case-insensitive, this can cause issues too.

**Comment by takboo** [comment]
Yes, I run repo on mac on exFAT at same Portable disk drive. repo is just a
python script. This issuse happened when repo want create symlink.

relan <notifications@github.com>于2017年6月21日 周三下午6:40写道：

**Comment by relan** [comment]
Could you create a small exFAT image on your Mac, make a symlink on it and share the whole image. I wonder how they do this.

**Comment by takboo** [comment]
I found my way out. I just repo a mirror on ubuntu on ext4. and then use this mirror as a repo server.
so i can repo it on mac on exFAT. thanks for your help.
