### ISSUE TITLE
Error mounting stderr: `ERROR: invalid VBR checksum 0x1b936469 (expected 0x21936477)

### ISSUE THREAD

**Issue by coreybruce** [relan/exfat#69]
Unable to Mount exfat drive on Ubuntu 16.04 LTS

Error mounting /dev/sda at /media/corey/PortableHDD1: Command-line `mount -t "exfat" -o "uhelper=udisks2,nodev,nosuid,uid=1000,gid=1000,iocharset=utf8,namecase=0,errors=remount-ro,umask=0077" "/dev/sda" "/media/corey/PortableHDD1"' exited with non-zero exit status 1:
stdout: `FUSE exfat 1.2.3
'
stderr: `ERROR: invalid VBR checksum 0x1b936469 (expected 0x21936477).
'.

**Comment by relan** [comment]
FS is corrupt. You can try experimental version of `exfatfsck` from the `repair` branch. It will fix this error, but there can be more.

**Comment by coreybruce** [comment]
So when will this issue be fixed?

**Comment by relan** [comment]
There's no issue in fuse-exfat code. It's a validity check that detected FS corruption. There's hardly possible to figure out why this happened, usually it's faulty hardware.

**Comment by coreybruce** [comment]
oh ok so you are saying it is actually a issue with either my exfat partition or portable HDD?

**Comment by relan** [comment]
Can't say for sure why this happened, but most probably yes. HDD failure, power failure, ejection without unmount often cause this error.

**Comment by coreybruce** [comment]
I had a friend confirm there was a bug and had the same issue, I don't know if it's been fixed yet also no it wasn't invalid.

**Comment by relan** [comment]
Any details?

**Comment by coreybruce** [comment]
Just pretty the same details as I gave really

**Comment by relan** [comment]
Operating system; what utility was used to create FS; what drivers used to write to this FS (e.g. a Sony camera, Windows 10 PC, etc.); steps to reproduce if you know how. That's what I mean by details.

**Comment by coreybruce** [comment]
Don't know the version of exfat it was but it was at the time but it was on
Xubuntu 16.04 LTS and just on a Seagate 1tb portable harddrive also
confirmed on Ubuntu or any Ubuntu based distro (at the time) also exfat
isn't supported on anything above Windows 7. Not sure if exfat has been
fixed after this time so I'd have to check again.
On 5 Sep. 2017 4:45 pm, "relan" <notifications@github.com> wrote:

Operating system; what utility was used to create FS; what drivers used to
write to this FS (e.g. a Sony camera, Windows 10 PC, etc.); steps to
reproduce if you know how. That's what I mean by details.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/relan/exfat/issues/69#issuecomment-327086051>, or mute
the thread

**Comment by notjames** [comment]
I was also running into the same error. 

```
root@vb-ubuntu:~# exfatfsck /dev/sdb
exfatfsck 1.2.5
ERROR: invalid VBR checksum 0x0 (expected 0x5ac480fc).
root@vb-ubuntu:~# lsblk -f
NAME                            FSTYPE      LABEL         UUID                                   MOUNTPOINT
...
                      exfat       jim_backup 0A16-42CD
├─sdb1                          exfat       jim_backup 0A16-42CD
└─sdb2                          exfat       jim_backup 0A16-42CD
sr0
```
Having found this thread, I decided to check out the `repair` branch of this repo. 

```
# /usr/local/sbin/exfatfsck /dev/sdb
exfatfsck 1.2.6
Checking file system on /dev/sdb.
ERROR: invalid VBR checksum 0x0 (expected 0x5ac480fc).
Fix (Y/N)? Y
File system version           1.0
Sector size                 512 bytes
Cluster size                128 KB
Volume size                4658 GB
Used space                 2844 GB
Available space            1814 GB

ERROR: failed to read cluster 0x159a378.
ERROR: failed to read cluster 0x1599ea6.
ERROR: failed to read cluster 0x15827fe.
ERROR: failed to read cluster 0x14c1f4b.
ERROR: failed to read cluster 0x12f2609.
ERROR: failed to read cluster 0x12f260c.
ERROR: failed to read cluster 0x12f260f.
ERROR: failed to read cluster 0x12f2612.
ERROR: failed to read cluster 0x12f2615.
ERROR: failed to read cluster 0x12f2618.
ERROR: failed to read cluster 0x12f261b.
ERROR: failed to read cluster 0x12f261e.
ERROR: failed to read cluster 0x12f2621.
ERROR: failed to read cluster 0x12f2624.
ERROR: failed to read cluster 0x12f2627.
ERROR: failed to read cluster 0x12f262a.
ERROR: failed to read cluster 0x12f262d.
ERROR: failed to read cluster 0x12f2630.
ERROR: failed to read cluster 0x12f2633.
ERROR: failed to read cluster 0x12f2636.
ERROR: failed to read cluster 0x12f2639.
ERROR: failed to read cluster 0x12f263c.
ERROR: failed to read cluster 0x12f263f.
ERROR: failed to read cluster 0x12f2642.
ERROR: failed to read cluster 0x140a69d.
ERROR: failed to read cluster 0x140a69e.
ERROR: failed to read cluster 0x14ad7db.
ERROR: failed to read cluster 0x14ad7de.
ERROR: failed to read cluster 0x1492758.
ERROR: failed to read cluster 0x148b310.
ERROR: failed to read cluster 0x1471433.
...
```

This is good er I mean, good to see some progress in attempting to fix the problem. This seems to truly indicate something might be up with the drive itself. We'll see. I'm going to let this finish. Hopefully, it will be able to complete the FS issue and mark the unreadable clusters bad or something. I appreciate the work done in this repo!

**Comment by relan** [comment]
@notjames, glad it worked! But checksum 0x0 and all those read errors are a very bad sign. I'd strongly recommend against using this drive as it seems to be defective.

**Comment by notjames** [comment]
@relan indeed. I'm going to copy the data from the bad drive to a new drive. Thanks for the heads up!!

**Comment by GrubbyHalo** [comment]
Just wanted to say that I had an exfat external drive that got corrupted when i put it into a colleagues win10 machine. I then used your repair branch and it fixed it! Excellent work. Thank you very much.

**Comment by oppaws** [comment]
Thank you so much! This saved my data

**Comment by jinhw1989** [comment]
Work like a charm, thanks.

**Comment by chept** [comment]
I have the same issue.
Does the `repair` branch still exists ? I am unable to find it.

**Comment by notjames** [comment]
It would appear that the repair/experimental branch is gone but I believe the changes were merged into master so `latest` should have the best version I believe. I could be wrong, though, so hopefully @relan can shed some light.

**Comment by relan** [comment]
> It would appear that the repair/experimental branch is gone but I believe the changes were merged into master so `latest` should have the best version I believe.

That's correct. 1.3.0 includes repair functionality.

**Comment by jeremy-rutman** [comment]
This solved my `invalid VBR checksum` , which I think may be caused by booting in windows, as well
