### ISSUE TITLE
Two short Questions

### ISSUE THREAD

**Issue by sebastianheyn** [relan/exfat#71]
Hi, 

I hope its OK to ask here, the readme stated to ask questions here ;-)
I use native exfat on windows to create SD cards that are used in WinCE devices. However, I was told to format the cards inside the winCE device which is a pain.

1) how close is mkfs.exfat to the microsoft specification? can it be used in a productive environment?
2) Any chance to make a Texfat? (exfat with tfat) with the utils? I didnt see an option 

I noticed that, on a 16GB (14.3gb real) SD card, the FS created with the utils uses 460kb, whereas the wince one is only like a 140kb. I used the same 8k cluster size on both formatting execs.

Any advice? Thanks!

**Comment by relan** [comment]
> how close is mkfs.exfat to the microsoft specification? can it be used in a productive environment?

mkfs.exfat produces images as close as possible to what Windows Vista does. I believe the code has been tested well enough to call it production-ready. But as usual, there's no warranty.

> Any chance to make a Texfat? (exfat with tfat) with the utils? I didnt see an option

TexFAT is not supported. I don't plan to implement it, but will happily merge anyone else's work.

> I noticed that, on a 16GB (14.3gb real) SD card, the FS created with the utils uses 460kb, whereas the wince one is only like a 140kb.

Probably different alignment and/or upper case conversion table. Shouldn't be a problem.

**Comment by sebastianheyn** [comment]
Thanks! This will make my life much easier... Have a nice weekend

**Comment by relan** [comment]
Thanks! You too.

Feel free to ask questions if they arise.
