### ISSUE TITLE
Mount is failed due to unexpected error

### ISSUE THREAD

**Issue by ethingstech** [relan/exfat#72]
As per the procedure given in https://github.com/relan/exfat, I have successfully installed the driver.
But I'm unable to mount the device

Error Snapshot:

root@WEY:/dev# mount.exfat-fuse /dev/sda1 /mnt/mmc_ovip/media/
/usr/bin/mount.exfat-fuse: line 2: ▒▒!{: not found
/usr/bin/mount.exfat-fuse: line 3: ▒▒!{: not found
/usr/bin/mount.exfat-fuse: line 4: ▒: not found
/usr/bin/mount.exfat-fuse: line 1: syntax error: unexpected word (expecting ")")

System Setup:
Linux version 3.10.53
gcc version 4.8.3

Could some one help on this issue?
Thanks.

**Comment by relan** [comment]
What Linux distro do you use?

What parameters did you pass to `./configure`?

Please post what this command prints:

    file /usr/bin/mount.exfat-fuse

**Comment by ethingstech** [comment]
Thanks for your comment. 
The problem is due to the make done on x86 and mount run on ARM target.
