### ISSUE TITLE
Remove error on "unsupported FAT count: 2"

### ISSUE THREAD

**Issue by shuffle2** [relan/exfat#77]
Currently I have to patch out this check locally in order to work with images which have it set. There does not seem to be any issues with doing so.

**Comment by relan** [comment]
2 FATs mean this is TexFAT. Since I don't know any details about it and don't have any devices supporting it, I'll not deal with TexFAT at all. Removal of this check may put users at the risk of data loss, so no.

**Comment by shuffle2** [comment]
Maybe allow read only mounting? Most Sony devices support this flavor of exfat (and since it works fine with the current fuse-exfat code, either they do not use any features you don't know of, or fuse-exfat doesn't complain when it encounters unknown things, which I hope is unlikely). Still, it doesn't seem very hard to do. Would you merge such a patch if I looked over the Sony impl and added whatever changes there might be to this project to ensure it's compatible?

**Comment by relan** [comment]
Would be nice if you could do some TexFAT reverse engineering since you have a device that supports it. If your patches are clear enough, I'll happily merge them.
