### ISSUE TITLE
Directory renaming when only the case differs

### ISSUE THREAD

**Issue by punit-arya** [relan/exfat#8]
As explained in your reply to the directory renaming issue here:
https://groups.google.com/forum/#!topic/exfat/rEbVXYhttQw
I don't understand why you have not highlighted this issue in the README file shipped with the package or just mentioned this in a BUGS file that could have been distributed along with the source code or binary package.  I have just lost a 219 GB folder just because of, well...

Thanks for contributing to the open source movement, Andrew.

**Comment by relan** [comment]
Data loss should never happen despite the known problem with case-insensitivity. Did you use v1.0.0? That version had a bug that caused loss of directory that was moved into itself (fixed in v1.0.1). Please explain in details how this happened.

**Comment by punit-arya** [comment]
Hi

Thanks for replying!

I am using Slackware 14.1 64-bit.  The slackbuild package that I used is the default v0.9.  This is a beta version I think.  So I guess I should have just used an updated one.  Here are the steps anyway:

<code>
<b>$</b> ls<p>
<i><b>HACKERSCHOOL/</b> some_files* some_directories/</i>
</code>
<code>
<b>$</b> mv HACKERSHOOL hackerschool
</code>
<code>
<b>$</b> ls<p>
<i>some_files*    some_directories/</i>
</code>

The output of 'df -h' shows that the disk usage has not reduced.  'ls -a' too doesn't show the file.

I have read the Google Groups post in which this bug was mentioned & after much Googling, I know by now that the directory is simply not recoverable unless an 'undeleting' or 'file recovery' software is used.  Are the files recoverable by any other means ?

However, I feel, a BUGS file is not a bad idea.

**Comment by relan** [comment]
v0.9.x versions are very old and they were not ready for prime time. As far as I can see SlackBuilds now provides v1.2.1, which is the latest version with all known bugs fixed.

I'm sorry about the data you've lost. Try PhotoRec.

I'll add a BUGS section to the man page, thanks for the suggestion!

**Comment by punit-arya** [comment]
My bad, v0.9 is what slackbuilds had when I downloaded it around a year ago.

Yes, photorec is my first choice.

I'll close this issue as resolved.  Thanks for your support :-).
