### ISSUE TITLE
Problems recovering corrupted microSD card

### ISSUE THREAD

**Issue by mistalro** [relan/exfat#82]
I have recovered a ddrescue image of a 128Gbyte microSD card and successfully recovered the various files (PDF and camera images) using testdisk and photorec utilities. But it is not possible to recover the file system through extfatfsck.

I have run gdb on this utility and the problem is that at: line 307 of main.c: 
ef->root_size = rootdir_size(ef);
the value of ef->root_size ise tset to zero. This triggers the end of processing and returns an ERROR

Is there any function that could attempt to recalculate the root size.

**Comment by relan** [comment]
> This triggers the end of processing and returns an ERROR

Which one? There are two cases in rootdir_size().

> Is there any function that could attempt to recalculate the root size.

That's what rootdir_size() does.

**Comment by relan** [comment]
8 month of silence, I guess the question is not relevant anymore.
