### ISSUE TITLE
ERROR: failed to read upper case table (5836 bytes starting at cluster 0x3).

### ISSUE THREAD

**Issue by defk** [relan/exfat#93]
hi, ubuntu 14.04

root@avs:~/datakam# dumpexfat -s /dev/sde1
Volume serial number      0xc494b212
FS version                       1.0
Sector size                      512
Cluster size                  131072
Sectors count              250052608
Clusters count                976640
First sector                   32768
FAT first sector               16384
FAT sectors count              16384
First cluster sector           32768
Root directory cluster             4
Volume state                  0x0000
FATs count                         1
Drive number                    0x80
Allocated space                   0%

root@avs:~/datakam# exfatfsck /dev/sde1
exfatfsck 1.2.8
ERROR: failed to read upper case table (5836 bytes starting at cluster 0x3).

root@avs:~/datakam# mount.exfat-fuse /dev/sdd1 /home/as/datakam/left/
FUSE exfat 1.2.8
ERROR: failed to read upper case table (5836 bytes starting at cluster 0x3).

**Comment by relan** [comment]
This means that OS returned I/O error to fuse-exfat. Most probably it's a hardware issue. Could you run `badblocks` against this device?

**Comment by defk** [comment]
О, Рашн Федерейшн :-)
Мой английский не очень хорош, поэтому напишу так.
В общем, чтению microsd с exfat, похоже, препятствовал видеорегистратор, в который эта карта была вставлена. Через картридер все работает.
Спасибо за помощь :-)

**Comment by relan** [comment]
Очень хорошо, что данные оказались в целости и сохранности.
