### ISSUE TITLE
Re-add ublio support for FreeBSD

### ISSUE THREAD

**Issue by fhajji** [relan/exfat#95]
Commit 3959f7deb323a26e8a5ae8c02251c7bee58cda6 removed ublio support for FreeBSD, wrongly stating that ublio is dead. This commit merely forced the ports maintainer of sysutils/fusefs-exfat to revert it locally by adding the following patch, relative to exfat-1.2.8:

https://svnweb.freebsd.org/ports/head/sysutils/fusefs-exfat/files/patch-ublio?revision=465414&view=markup

From the look of it, it essentially reverts commit 3959f7deb323a26e8a5ae8c02251c7bee58cda6.

Running this port here on a 3 weeks old FreeBSD 11.2-BETA2:

FreeBSD monster 11.2-BETA2 FreeBSD 11.2-BETA2 #1 r334062: Tue May 22 23:46:29 CEST 2018     root@monster:/usr/obj/usr/src/sys/GENERIC  amd64

It would be nice to re-add ublio support for us FreeBSD users here upstream. Thanks.

**Comment by relan** [comment]
ublio was re-added in b3a89e347b281bc33e8fc9daf214e9618f924fa6. I'll keep this issue open until I make a new release.

**Comment by relan** [comment]
Done in v1.3.0.
