### ISSUE TITLE
Support -a option

### ISSUE THREAD

**Issue by scolby33** [relan/exfat#98]
Over at https://github.com/systemd/systemd/issues/9849#issuecomment-412038398, the maintainers think that an `-a` option is "not unreasonable to expect" from an fsck implementation; in fact their `systemd-fsck` implementation assumes that one is present.

When invoked with `-a`, other the fsck's for other filesystems "automatically repair the file system", according to the manual for `e2fsck`. `-a` has been deprecated in favor of `-p`, but systemd still uses the old version.

Is it possible to add an `-a` option for the sake of systemd compatibility?

**Comment by scolby33** [comment]
`fsck.cramfs` has functionality to silently ignore several common fsck arguments that it doesn't need to use, including `-a`: http://man7.org/linux/man-pages/man8/fsck.cramfs.8.html

**Comment by relan** [comment]
> Is it possible to add an `-a` option for the sake of systemd compatibility?

Sure.

In fact `-a` is already supported in the _repair_ branch along with actual functionality.

**Comment by scolby33** [comment]
Oh! I'm sorry I didn't see this at first--I only did a cursory look before opening the issue. Apologies for that.

What is the status of the *repair* branch? Is switching to that something that I should advocate to my distro (Arch, in this case), or is it not in a production-ready state? If not I can continue to judiciously ignore the error messages systemd throws at me but this time with more knowledge.

**Comment by relan** [comment]
The _repair_ branch needs some more testing before I can merge it. I'd suggest to wait until a new stable version of exfat-utils is out.

**Comment by relan** [comment]
Done in v1.3.0.

**Comment by scolby33** [comment]
Thank you!
